import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="header">
          <p>This is the header content.</p>
        </div>
        <div className="container">
          <div className="sidebar">
            <h2>Sidebar</h2>
            <p>This is the sidebar content.</p>
          </div>
          <div className="content">{children}</div>
        </div>
        <div className="footer">
          <p>This is the footer content.</p>
        </div>
      </body>
    </html>
  );
}
